#!/usr/bin/env bash

# Check if script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be run as root" >&2
    exit 1
fi

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
echo 'frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web-01 54.144.134.238:80 check
        server web-02 18.234.80.114:80 check
' | tee /etc/haproxy/haproxy.cfg > /dev/null

# Start HAProxy
systemctl start haproxy

# Enable HAProxy to start on boot
systemctl enable haproxy
