#!/usr/bin/env bash
#configure nginx server to listen for port 80
#this is spam
#this is spam
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
