#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak
sudo bash -c 'echo "127.0.0.2       localhost" > /etc/hosts.new'
sudo bash -c 'echo "8.8.8.8        facebook.com" >> /etc/hosts.new'
sudo mv /etc/hosts.new /etc/hosts

echo "IP addresses configured. Check the changes using 'ping'."

# Provide instructions for reverting the changes
echo "Note: If you want to revert changes, use the command 'sudo cp /etc/hosts.bak /etc/hosts'."
